name: my_tasker
description: "মাই ট্যাস্কার - পড়াশোনার পরিকল্পনা ও অভ্যাস ট্র্যাকার"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # Local database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Charts
  fl_chart: ^0.69.0

  # Animations
  flutter_animate: ^4.5.0

  # Image
  image_picker: ^1.1.2

  # Notifications
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4

  # PDF Report generation
  pdf: ^3.11.1
  printing: ^5.13.1
  path_provider: ^2.1.4

  # Utils
  uuid: ^4.5.1
  intl: ^0.19.0
  permission_handler: ^11.3.1
  crypto: ^3.0.5
  connectivity_plus: ^6.1.1
  http: ^1.2.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true



  fonts:
    - family: AbuJMAkkas
      fonts:
        - asset: assets/fonts/AbuJMAkkas.ttf
        - asset: assets/fonts/AbuJMAkkasItalic.ttf
          style: italic

  assets:
    - assets/fonts/
    - assets/images/
